### PR TITLE
Fix EZP-26298 / Request #11118: Sporadic 500 Errors on Platform.sh

### PR DESCRIPTION
**Pull request by glye**
Workaround: Disable Redis, use file based cache for now.

https://jira.ez.no/browse/EZP-26298
https://platformsh.zendesk.com/requests/11118

### CODE REVIEW

**Comment by DavidLiedle** [comment]
+1

**Comment by andrerom** [comment]
Notes:
- this means single server setup
- "inMemory" flag has nothing todo with redis

**Comment by glye** [comment]
Single server only is known, yes. I misunderstood the inMemory flag. Anyway, given what I hear from the platformsh slack it seems we can have Redis back very soon, possibly today.

**Comment by damz** [comment]
We deployed a fix yesterday (for the EU region) that should lower the jitter in Redis latency that you were experiencing. The same fix is being deployed to the US region this morning.

That said, as I mentioned in the support ticket, it doesn't make much sense to me to have a 100ms timeout for Redis commands. It looks like it is just the default from `tedious/Stash` that you are just inheriting, but you should consider changing it. It is a bit pointless to fail the whole request if Redis happens to be a bit slower than usual (and I assume you are not doing the same type of fail-fast for MySQL...).

**Comment by glye** [comment]
Thanks @damz! I confirm that Redis is working today, and we should revert this PR (after a bit more testing). What you say about the timeout makes sense too.

**Pull request merged**
